version: '3.8'
services:
  node:
    image: cl-itau-bff-tesoreria:development
    build:
      context: .
      dockerfile: ./Dockerfile
      target: development
    ports:
      - "${HOST_PORT}:${PORT}"
    env_file:
      - .env
    volumes:
      - "./:/usr/src/app"
      - "/usr/src/app/node_modules"
    command: npm run start:dev
    networks:
      - united-containers
networks:
  united-containers:
    external: true